# Example of Fleet-enrolled Elastic Agent pre-configured with an agent policy
# for running the APM Server integration (see kibana.yml).
#
# Run with
#   docker compose \
#     -f docker-compose.yml \
#     -f extensions/fleet/fleet-compose.yml \
#     -f extensions/fleet/agent-apmserver-compose.yml \
#     up

services:
  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server-wolfi:${STACK_VERSION}
    volumes:
      - ./apm-server:/usr/share/apm-server/state:Z
      - ./certs:/usr/share/apm-server/config/certs:z
    environment:
      FLEET_ENROLL: '1'
      FLEET_TOKEN_POLICY_NAME: Agent Policy APM Server
      FLEET_INSECURE: '1'
      FLEET_URL: https://fleet-server:8220
      # Enrollment.
      # (a) Auto-enroll using basic authentication
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
      # (b) Enroll using a pre-generated enrollment token
      #FLEET_ENROLLMENT_TOKEN: <enrollment_token>
    ports:
      - 8200:8200
    hostname: apm-server
    # Elastic Agent does not retry failed connections to Kibana upon the initial enrollment phase.
    restart: on-failure
    networks:
      - elastic
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      fleet-server:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: ${APM_MEM_LIMIT}
          cpus: ${APM_CPU_LIMIT}
        reservations:
          memory: ${APM_MEM_RESV}
          cpus: ${APM_CPU_RESV}
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl --cacert /usr/share/kibana/config/certs/ca/ca.crt -s -I http://localhost:8220 | grep -q 'HTTP/2 302'",
    #     ]
      interval: 10s
      timeout: 10s
      retries: 120
