# Based on official Elasticsearch docker-compose.yml

services:
  setup:
    container_name: setup
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:${STACK_VERSION}
    networks:
      - elastic
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs:z
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_SYSTEM_PASSWORD} == x ]; then
          echo "Set the KIBANA_SYSTEM_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: elasticsearch\n"\
          "    dns:\n"\
          "      - elasticsearch\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: fleet-server\n"\
          "    dns:\n"\
          "      - fleet-server\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: apm-server\n"\
          "    dns:\n"\
          "      - apm-server\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R 1000:1000 config/certs;
        find . -type d -exec chmod 777 \{\} \;;
        find . -type f -exec chmod 666 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_SYSTEM_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: [ "CMD-SHELL", "[ -f config/certs/elasticsearch/elasticsearch.crt ]" ]
      interval: 1s
      timeout: 5s
      retries: 120

  elasticsearch:
    container_name: elasticsearch
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:${STACK_VERSION}
    networks:
      - elastic
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs:z
      - ./esdata01:/usr/share/elasticsearch/data:z
    # ports:
    #   - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=${CLUSTER_NAME}
      #- cluster.initial_master_nodes=elasticsearch
      #- cluster.initial_master_nodes=es01,es02,es03
      #- discovery.seed_hosts=es02,es03
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
      - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.ml.use_auto_machine_memory_percent=true
    deploy:
      resources:
        limits:
          memory: ${ES_MEM_LIMIT}
          cpus: ${ES_CPU_LIMIT}
        reservations:
          memory: ${ES_MEM_RESV}
          cpus: ${ES_CPU_RESV}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'" ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
      # es02:
      #   condition: service_healthy
      # es03:
      #   condition: service_healthy
    image: docker.elastic.co/kibana/kibana-wolfi:${STACK_VERSION}
    networks:
      - elastic
    volumes:
      - ./certs:/usr/share/kibana/config/certs:z
      - ./kibanadata:/usr/share/kibana/data:z
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      - ELASTICSEARCH_PUBLICBASEURL=https://${SERVER_NAME}:${ES_PORT}

      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana/kibana.key
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana/kibana.crt

      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${SAVED_OBJECTS_ENCRYPTIONKEY}
      - XPACK_SECURITY_ENCRYPTIONKEY=${SECURITY_ENCRYPTIONKEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${REPORTING_ENCRYPTIONKEY}
    deploy:
      resources:
        limits:
          memory: ${KIBANA_MEM_LIMIT}
          cpus: ${KIBANA_CPU_LIMIT}
        reservations:
          memory: ${KIBANA_MEM_RESV}
          cpus: ${KIBANA_CPU_RESV}
    healthcheck:
      test: [ "CMD-SHELL", "curl --cacert /usr/share/kibana/config/certs/ca/ca.crt -s -I https://localhost:5601 | grep -q 'HTTP/2 302'" ]
      interval: 10s
      timeout: 10s
      retries: 120

  nginx:
    container_name: nginx
    depends_on:
      kibana:
        condition: service_healthy
      # fleet:
      #   condition: service_healthy
    image: nginx:stable-alpine-slim
    networks:
      - elastic
    restart: unless-stopped
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:Z,ro
      - ./nginx/conf/conf.d:/etc/nginx/conf.d:Z
      - ./nginx/conf/templates:/etc/nginx/templates:Z,ro
      - ./nginx/log:/var/log/nginx:z
      - ./nginx/certs:/certs:z,ro
    ports:
      - 80:80
      - 443:443
      - ${ES_PORT}:9200
      - ${FLEET_PORT}:8220
    environment:
      - SERVER_NAME=${SERVER_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/wget --no-verbose --tries=1 --spider http://localhost/ || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 120
    deploy:
      resources:
        limits:
          memory: ${NGINX_MEM_LIMIT}
          cpus: ${NGINX_CPU_LIMIT}
        reservations:
          memory: ${NGINX_MEM_RESV}
          cpus: ${NGINX_CPU_RESV}

networks:
  elastic:
    driver: bridge
    ipam:
      config:
        - subnet: 100.64.0.0/24
